source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.1'
project 'EDCore'
use_frameworks!

target 'EDCore_Example' do
  pod 'EDCore', :path => '../'
end

#target 'TDCore_Tests', :exclusive => true do
#  pod "TDCore", :path => "../"
#
#  pod 'Specta'
#  pod 'Expecta'
#  pod 'FBSnapshotTestCase'
#  pod 'Expecta+Snapshots'
# end
