source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'
project 'EDCore'

target 'EDCore_Example' do
  pod 'EDCore', :path => '../'
end

# target 'TDCore_Tests', :exclusive => true do
#   pod "TDCore", :path => "../"
#
#   pod 'Specta'
#   pod 'Expecta'
#   pod 'FBSnapshotTestCase'
#   pod 'Expecta+Snapshots'
# end
